{
  "apiVersion": "v1",
  "clusters":
    [
      {
        "cluster":
          {
            "certificate-authority-data": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJZWdyY3kwWkVUTGt3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBeE1Ea3hNRFF6TXpCYUZ3MHpOREF4TURZeE1EUTRNekJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNrR0NobkNkT1oyT3BLa294OSt4VFJvKzY1VnVNRVpxeEN5WldxbzhYNjZ2OENPeDY4M3BIOVZsRWUKSXNDZzdTNGtWT0QxTjduRU11emxrTHV1ekRBblRxTmVkK2lxd1d0c0EveFlwYlpEV2dhQ3JFZCtxbEkrTVR6SApqVEVQS2luYnBBNCtDcnZ3WmErbDhhVk95eTFBWGl1ZWZoSHZvcm9LbG5Bb1FYNzlOSHFDd2wxWkJCeXk0YW5yCjM0Qnh3d1YvNXVuQy85MVUxUGlZTERFUEtzVGlLR0Q5Q2plM0xhaFFHRENYZzZyKzBLNHRodnBrdXFkdzVKUVAKamh5OW5RU0JxSkFGVll5dExWQlNMZ2l5RFByNVFJOXpVS2NmaHBZQWI2aTZwZFkvYXJ2VkhmaEtCNmg4NE1VcgplYzg5ODN5SC9aS2cvblpxUVhZS050Z0dONXhYQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUbmZCWnpKbE1Mbm13SVlpazd4VFBRTkEwZ1J6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkZGcStEK01tawpFSHBPOVBodzFPZjJSZEQyMmRrbklZSjlSNEg1N0gzUnNtaDR3ZlV0TUJ4SFpaVzAzSitPaXJUQTF0aUNFU0ZQCmtFUWxDRUJCM0c4MVF4bjZJdlBNSVczakY3ZTk2TlpVaVpHZHFaa0dSL0NDaVY3TlU1dlFnN09uSUdUeXdWRnEKb0h3U0pLWGFkenFRNWtsSFlhUC9uZzhsK1drdkpjL0Q1R1ZIWkozT2hDbWFuK1cyU3o0QXpCQWhnalVPalpqdQpvMWgrT3BINm41Sld1aGNVWEtmb0UzZnpKdk1PZ2I3Ry9LVzJGOEpXVVpsbTVQb2h3eUZVQWVJUCtvdWJrMWxTCmErTHBZNndRcVRWVmZMbCtFYTZqMFJZbGFoUTY5ZDlMTFh6K2VlcnBoL0RWYXpSSFg1Q1cvM1JKamRiNjhBUDEKRkxUSEEvd2xiai9YCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K",
            "server": "https://49AD9842050A66AD1098FA66299784E9.sk1.eu-west-2.eks.amazonaws.com",
          },
        "name": "kubernetes",
      },
    ],
  "contexts":
    [{ "context": { "cluster": "kubernetes", "user": "aws" }, "name": "aws" }],
  "current-context": "aws",
  "kind": "Config",
  "users":
    [
      {
        "name": "aws",
        "user":
          {
            "exec":
              {
                "apiVersion": "client.authentication.k8s.io/v1beta1",
                "args":
                  [
                    "eks",
                    "get-token",
                    "--cluster-name",
                    "cluster-eksCluster-3a1a180",
                  ],
                "command": "aws",
                "env":
                  [
                    {
                      "name": "KUBERNETES_EXEC_INFO",
                      "value": '{"apiVersion": "client.authentication.k8s.io/v1beta1"}',
                    },
                  ],
              },
          },
      },
    ],
}
